import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import CloudNRGSidebar from "@/components/cloudnrg-sidebar";
import CloudNRGHeader from "@/components/cloudnrg-header";
import CloudNRGFooter from "@/components/cloudnrg-footer";
import {Toaster} from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
      >
          <SidebarProvider>
              <CloudNRGSidebar variant="inset"/>
              <SidebarInset>
                  <main className={`grid min-h-full`} style={{ gridTemplateRows : "auto 1fr auto"}}>
                      <CloudNRGHeader/>
                      {children}
                      <CloudNRGFooter/>
                  </main>
                  <Toaster position="bottom-right" expand={false}  richColors  />
              </SidebarInset>
          </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
